Repository AspireUni/Aspire, pull requests merged in 2020-07, with the labels that each got.

#92 fix: lines_longer_than_80_chars errors + clean-up
  .gitignore
  analysis_options.yaml
  ios/Podfile
  ios/Podfile.lock
  lib/chat/chat_messenger.dart
  lib/chat/message.dart
  lib/chat/new_matches.dart
  lib/chat/user_message_rows.dart
  lib/ftu/filters.dart
  lib/ftu/signuplogin.dart
  lib/navigation/app_controller.dart
  lib/profile/sections/contact.dart
  lib/profile/sections/education.dart
  lib/profile/sections/experience.dart
  lib/profile/sections/section.dart
  mentorApp/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  mentorApp/ios/Runner.xcworkspace/xcuserdata/nprakash2.xcuserdatad/UserInterfaceState.xcuserstate
  pubspec.lock
Labels: chore

#91 feat: add edit profile
  lib/constants/profile_constants.dart
  lib/main.dart
  lib/navigation/app_controller.dart
  lib/navigation/root.dart
  lib/profile/common/add_row_button.dart
  lib/profile/common/app_bar.dart
  lib/profile/common/date_picker.dart
  lib/profile/common/delete_button.dart
  lib/profile/common/input_field.dart
  lib/profile/common/job_row.dart
  lib/profile/common/list_picker.dart
  lib/profile/common/picker_field.dart
  lib/profile/common/school_row.dart
  lib/profile/common/section.dart
  lib/profile/common/skill_row.dart
  lib/profile/common/styles.dart
  lib/profile/edit_profile/edit_profile.dart
  lib/profile/edit_profile/sections/contact/edit_contact.dart
  lib/profile/edit_profile/sections/education/edit_education.dart
  lib/profile/edit_profile/sections/education/save_education.dart
  lib/profile/edit_profile/sections/experience/edit_experience.dart
  lib/profile/edit_profile/sections/experience/save_experience.dart
  lib/profile/edit_profile/sections/skills/edit_skills.dart
  lib/profile/edit_profile/sections/skills/save_skill.dart
  lib/profile/edit_profile/sections/summary/edit_summary.dart
  lib/profile/header.dart
  lib/profile/sections/education.dart
  lib/profile/sections/experience.dart
  lib/profile/sections/skills.dart
  lib/profile/view_profile/header.dart
  lib/profile/view_profile/sections/contact.dart
  lib/profile/view_profile/sections/education.dart
  lib/profile/view_profile/sections/experience.dart
  lib/profile/view_profile/sections/header.dart
  lib/profile/view_profile/sections/sections.dart
  lib/profile/view_profile/sections/skills.dart
  lib/profile/view_profile/sections/summary.dart
  lib/profile/view_profile/user_profile.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#94 fix: pairings header
  ios/Podfile.lock
  lib/chat/chat_messenger.dart
  lib/chat/user_message_rows.dart
  lib/common/format_text.dart
  lib/common/global_header/global_header.dart
  lib/constants/chat_constants.dart
  lib/constants/common_constants.dart
  lib/constants/global_header/global_header_constants.dart
  lib/pairings/pairings.dart
  pubspec.lock
Labels: fix

#104 feat: fade-in splash screen + refactor root
  images/logos/dark_logo_transparent.png
  images/logos/light_logo_transparent.png
  images/logos/logo_dark_bg.png
  lib/constants/theme_constants.dart
  lib/ftu/rootpage.dart
  lib/main.dart
  lib/navigation/root.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#111 chore: move docs to folder + fix codecov badge
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
  notes.md
Labels: chore

#110 feat: sign up funnel page
  images/sign_up/ano_hands_up.png
  lib/common/global_header.dart
  lib/constants/common_constants.dart
  lib/constants/ftu_constants.dart
  lib/ftu/login_create_account/login.dart
  lib/ftu/login_create_account/login_create_account.dart
  lib/ftu/sign_up/funnel.dart
  pubspec.yaml
Labels: feature

#121 feat: reset password screens
  images/sign_up/ano_hands_side.png
  images/sign_up/ano_hands_straight_up.png
  lib/authentication/firebase_authentication.dart
  lib/authentication/login.dart
  lib/authentication/password/link_sent.dart
  lib/authentication/password/reset_link.dart
  lib/authentication/sign_up/funnel.dart
  lib/authentication/sign_up/mentee_sign_up.dart
  lib/constants/authentication_constants.dart
Labels: DO NOT MERGE, feature

#122 chore: delete unused images
  flutter_01.png
  flutter_02.png
  images/DefaultBg.png
  images/PairingsBg.png
  images/app_icon.png
  images/hello.png
  images/hellobig.jpg
  images/logos/dark_logo_transparent.png
  images/splash_screen_icon.png
  lib/constants/pairings_constants.dart
  lib/navigation/root.dart
  pubspec.yaml
Labels: chore
