Repository AspireUni/Aspire, pull requests merged in 2020-06, with the labels that each got.

#74 chore: add effective dart linter
  analysis_options.yaml
  pubspec.lock
  pubspec.yaml
Labels: chore

#69 feat: card component + swipe gesture
  images/PairingsBg.png
  lib/constants/pairings_constants.dart
  lib/dashboard/dashboard.dart
  lib/navigation/app_controller.dart
  lib/pairings/pairings.dart
  lib/pairings/pairings_card.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#75 fix: avoid_positional_boolean_parameters errors
  analysis_options.yaml
  lib/chat/chat_messenger.dart
  lib/pairings/pairings_card.dart
  lib/profile/sections/contact.dart
  lib/profile/sections/education.dart
  lib/profile/sections/experience.dart
  lib/profile/sections/skills.dart
Labels: fix

#76 fix: avoid_types_on_closure_parameters errors
  analysis_options.yaml
  lib/pairings/pairings_card.dart
  test/chat/chat_test.dart
  test/dashboard/dashboard_test.dart
  test/ftu/filters_test.dart
  test/ftu/signup_test.dart
  test/main_test.dart
  test/navigation/app_controller_test.dart
  test/navigation/root_test.dart
  test/profile/user_profile_test.dart
Labels: fix

#77 fix: directives_ordering errors
  analysis_options.yaml
  lib/chat/new_matches.dart
  lib/chat/user_message_rows.dart
  lib/navigation/root.dart
Labels: fix

#80 fix: unnecessary_new lint errors
  analysis_options.yaml
  lib/chat/chat_messenger.dart
  lib/chat/new_matches.dart
  lib/chat/user_message_rows.dart
  lib/ftu/filters.dart
  lib/profile/sections/education.dart
  lib/profile/sections/experience.dart
  lib/profile/sections/skills.dart
Labels: fix

#81 fix: prefer_relative_imports errors
  analysis_options.yaml
  lib/profile/header.dart
  lib/profile/sections/contact.dart
  lib/profile/sections/education.dart
  lib/profile/sections/experience.dart
  lib/profile/sections/skills.dart
  lib/profile/sections/summary.dart
Labels: fix

#83 fix: prefer_final_fields + prefer_interpolation_to_compose_strings
  analysis_options.yaml
  lib/navigation/app_controller.dart
  lib/profile/sections/contact.dart
  lib/profile/sections/education.dart
  lib/profile/sections/experience.dart
Labels: fix

#78 fix: prefer_collection_literals + non_bool_condition errors
  analysis_options.yaml
  lib/chat/chat_messenger.dart
  lib/chat/new_matches.dart
  lib/chat/user_message_rows.dart
  lib/profile/sections/education.dart
  lib/profile/sections/experience.dart
  lib/profile/sections/skills.dart
Labels: fix

#88 feat: populate firestore with dummy data
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/Runner/GoogleService-Info.plist
  lib/ftu/signup.dart
  lib/helpers/dummy_data.dart
  lib/helpers/users.dart
  lib/main.dart
  lib/navigation/root.dart
  pubspec.lock
Labels: feature

#89 feat: login + signup page
  images/Logo.png
  ios/Podfile
  ios/Podfile.lock
  lib/constants/signuplogin_constants.dart
  lib/ftu/authentication.dart
  lib/ftu/rootpage.dart
  lib/ftu/signuplogin.dart
  lib/main.dart
  lib/navigation/app_controller.dart
  lib/navigation/root.dart
  pubspec.lock
  pubspec.yaml
Labels: feature
