Repository AspireUni/Aspire, pull requests merged in 2020-05, with the labels that each got.

#11 feat: nav bar and screen navigation
  mentorApp/lib/AppController.dart
  mentorApp/lib/Chat/Chat.dart
  mentorApp/lib/Dashboard/Dashboard.dart
  mentorApp/lib/Profile/UserProfile.dart
  mentorApp/lib/main.dart
  mentorApp/pubspec.lock
  mentorApp/pubspec.yaml
  mentorApp/test/WidgetTest.dart
Labels: feature

#12 chore: add muli typeset from google fonts
  mentorApp/ios/Flutter/Debug.xcconfig
  mentorApp/ios/Flutter/Release.xcconfig
  mentorApp/ios/Podfile
  mentorApp/pubspec.lock
  mentorApp/pubspec.yaml
Labels: chore

#13 chore: upgrade sdk
  mentorApp/pubspec.yaml
Labels: chore

#15 feat: creating initial routes
  .vscode/launch.json
  CONTRIBUTING.md
  mentorApp/README.md
  mentorApp/lib/AppController.dart
  mentorApp/lib/Profile/UserProfile.dart
  mentorApp/lib/SignUp/FTU.dart
  mentorApp/lib/SignUp/Filters.dart
  mentorApp/lib/main.dart
  mentorApp/notes.md
Labels: feature

#16 feat: header, description, and name on dashboard
  mentorApp/images/DashboardBg.png
  mentorApp/images/DefaultBg.png
  mentorApp/ios/Runner.xcodeproj/project.pbxproj
  mentorApp/lib/AppController.dart
  mentorApp/lib/Dashboard/Dashboard.dart
  mentorApp/pubspec.yaml
  mentorApp/test/Dashboard/DashboardTest.dart
Labels: feature

#19 feat: added emulator with different sizes
  mentorApp/lib/Navigation/AppController.dart
  mentorApp/lib/Navigation/Root.dart
  mentorApp/lib/main.dart
  mentorApp/pubspec.lock
  mentorApp/pubspec.yaml
Labels: feature

#25 chore: add firebase setup for iOS
  mentorApp/ios/Podfile.lock
  mentorApp/ios/Runner.xcodeproj/project.pbxproj
  mentorApp/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  mentorApp/ios/Runner/GoogleService-Info.plist
  mentorApp/lib/main.dart
  mentorApp/pubspec.lock
  mentorApp/pubspec.yaml
Labels: chore

#21 feat: travisCI build
  README.md
  mentorApp/.travis.yaml
Labels: DO NOT MERGE, feature

#45 chore: add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: chore

#46 chore: update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#47 chore: delete duplicate files + comments
  lib/Chat/Chat.dart
  lib/Dashboard/Dashboard.dart
  lib/FTU/Filters.dart
  lib/FTU/SignUp.dart
  lib/Navigation/Root.dart
  lib/Navigation/app_controller.dart
  lib/ftu/filters.dart
  lib/ftu/signup.dart
Labels: chore

#52 fix: android build
  android/app/build.gradle
  pubspec.lock
Labels: bug fix

#53 feat: user profile view
  lib/profile/header.dart
  lib/profile/icon_button.dart
  lib/profile/section_icons.dart
  lib/profile/sections/bio.dart
  lib/profile/sections/info.dart
  lib/profile/sections/skills.dart
  lib/profile/user_profile.dart
  pubspec.yaml
Labels: feature

#49 chore: add .circleci/config.yml
  .circleci/config.yml
Labels: feature

#60 feat: create interactive messenger view
  lib/chat/chat_messenger.dart
  lib/chat/messages.dart
  lib/chat/new_matches.dart
Labels: feature
